version: '3'
services:
  db:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: crud_nodejs_db
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db


